# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c12afdbfdc3f12e17bc26614a334cf5b9a8b74918b32ac493f9efd61f139053750b6443f546b419d85d9ea16755268e0a847a87849f3386ac0961b5fee98a9a5

test:
  secret_key_base: 2c7a7021c28294c5ad420e3189976962796f2b28c8256677f7f3a33abfd593eaf02b781b83e4b329cc402510369a6d80b862bfa5dc21ad7cbd3c5393d4b24e40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
